### ISSUE TITLE
Take user input for port

### ISSUE THREAD

**Issue by achhayapathak** [achhayapathak/termtalk#16]
Right now the PORT on which the server is hosted is hardcoded. Take PORT no as input from the user and check if it is correct and available then host a server on that port otherwise display an error message.

**Comment by yashkathe** [comment]
Hey @achhayapathak  can you assign this issue to me?

P.S.I tested your code and I like your project, I will keep contributing to opened issues

**Comment by achhayapathak** [comment]
Hi @yashkathe, I would be more than happy if you contribute to the project. Though couple of things I would like to mention before you start contributing:
1. Please read about software versioning here: https://semver.org/ . In this project, I am following the MAJOR.MINOR.PATCH versioning format and I update the version of the application in the package.json file everytime I make a commit. This has to be done as we are developing an npm package where versioning is important. So whenever you make a commit make sure to update the version according to the change.
2. Please follow the standard commit message format that I am using, here is an example: v1.3.8 bug-fix: removed the provenance flag. It starts with the current version and then mentions whether the update was a bug-fix, an enhancement or a feature and then you provide the description of the change.

**Comment by yashkathe** [comment]
> Hi @yashkathe, I would be more than happy if you contribute to the project. Though couple of things I would like to mention before you start contributing:
> 
>     1. Please read about software versioning here: https://semver.org/ . In this project, I am following the MAJOR.MINOR.PATCH versioning format and I update the version of the application in the package.json file everytime I make a commit. This has to be done as we are developing an npm package where versioning is important. So whenever you make a commit make sure to update the version according to the change.
> 
>     2. Please follow the standard commit message format that I am using, here is an example: v1.3.8 bug-fix: removed the provenance flag. It starts with the current version and then mentions whether the update was a bug-fix, an enhancement or a feature and then you provide the description of the change.

Can you create a contributions.md file, so that it is easier for new developers to follow these rules

**Comment by achhayapathak** [comment]
I have added some instructions in the Readme file but in case you want to contribute there as well I will be more than happy!
