### ISSUE TITLE
Port validation on client side

### ISSUE THREAD

**Issue by achhayapathak** [achhayapathak/termtalk#21]
Whenever I run `npm run join` and enter a port on which a server is not hosted, the application goes into 'Trying to connect to server on PORT XXXX ...' state. Rather we should see a message like 'No server is hosted on this port, please try a different one!' and the user should be prompted to enter the port number again.

**Comment by achhayapathak** [comment]
@yashkathe would you like to take this up?

**Comment by yashkathe** [comment]
> @yashkathe would you like to take this up?

Yup I'll take this one
